### ISSUE TITLE
Can't figure out how to enable global time sync. please help

### ISSUE THREAD

**Issue by GigaBite2001** [tommaier123/UdonSharpDayNightController#3]
I want the Day/Night cycle to sync for everyone in the world, but I don't know how to enable it, please help. Thank you.

**Comment by tommaier123** [comment]
It should sync if the local variable is set to false. Keep in mind that only the instance owner can change the global time.

**Comment by GigaBite2001** [comment]
> It should sync if the local variable is set to false. Keep in mind that only the instance owner can change the global time.

How do I set it to false by default?

**Comment by tommaier123** [comment]
It's false by default

**Comment by GigaBite2001** [comment]
Oh. Well then how do I change it? 'cause I must've made it true somehow.

**Comment by tommaier123** [comment]
This is not supposed to be a dropin module otherwise I would have actually made it a module. The code is exactly how I used it with all the features I used, most of which are unnecessary for other use cases. It is supposed to be taken as reference/inspiration. Most of the code is outdated by now too. In order to make it work you need to know a bit of Unity and some coding, best case you should not use any of this code and rewrite everything in a better way.

**Comment by GigaBite2001** [comment]
unfortunately that's not going to work, 'cause I don't know how to code like that. Thanks you for your time. I'll try to get it working globally. Thanks again.
